version: '3'
services:
  mysql_maestros:
    image: mysql:5.7
    container_name: maestro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3309:3306"
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica

  mysql_esclavo:
    image: mysql:5.7
    container_name: esclavo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3308:3306"
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "msql_maestro, msql_esclavo"
      PMA_ARBITRARY: 1